// products.ts

export interface Product {
  id: number;
  name: string;
  description: string;
  price: number;
  image: string;
  category: string;
  animalType: string;
  isPet: boolean;
}

/* ================================
   Productos para Mascotas
   ================================ */
// Para el grupo de mascotas usaremos tres tipos de animales:
// "Perros", "Gatos" y "Hámsters", y las categorías:
// "Alimentos", "Accesorios", "Complementos" y "Salud".

export const productsForPets: Product[] = [
  // ----- PERROS -----
  // Categoría: Alimentos
  {
    id: 101,
    name: "Pienso Premium para Perros",
    description: "Alimento premium para perros de alta calidad",
    price: 50,
    image: "/images/perro-alimento-1.jpg",
    category: "Alimentos",
    animalType: "Perros",
    isPet: true,
  },
  {
    id: 102,
    name: "Pienso Económico para Perros",
    description: "Alimento balanceado a buen precio para perros",
    price: 30,
    image: "/images/perro-alimento-2.jpg",
    category: "Alimentos",
    animalType: "Perros",
    isPet: true,
  },
  // Categoría: Accesorios
  {
    id: 103,
    name: "Collar para Perros",
    description: "Collar ajustable y cómodo para perros",
    price: 20,
    image: "/images/perro-collar-1.jpg",
    category: "Accesorios",
    animalType: "Perros",
    isPet: true,
  },
  {
    id: 104,
    name: "Correa para Perros",
    description: "Correa resistente para paseos seguros",
    price: 25,
    image: "/images/perro-correa-1.jpg",
    category: "Accesorios",
    animalType: "Perros",
    isPet: true,
  },
  // Categoría: Complementos
  {
    id: 105,
    name: "Suplemento para Perros",
    description: "Suplemento vitamínico para potenciar la salud",
    price: 35,
    image: "/images/perro-suplemento-1.jpg",
    category: "Complementos",
    animalType: "Perros",
    isPet: true,
  },
  {
    id: 106,
    name: "Complemento Dietético para Perros",
    description: "Complemento para mejorar la dieta diaria",
    price: 40,
    image: "/images/perro-complemento-1.jpg",
    category: "Complementos",
    animalType: "Perros",
    isPet: true,
  },
  // Categoría: Salud
  {
    id: 107,
    name: "Vacuna para Perros",
    description: "Vacuna preventiva esencial para perros",
    price: 60,
    image: "/images/perro-vacuna-1.jpg",
    category: "Salud",
    animalType: "Perros",
    isPet: true,
  },
  {
    id: 108,
    name: "Antipulgas para Perros",
    description: "Tratamiento eficaz contra pulgas y garrapatas",
    price: 45,
    image: "/images/perro-antipulgas-1.jpg",
    category: "Salud",
    animalType: "Perros",
    isPet: true,
  },

  // ----- GATOS -----
  // Categoría: Alimentos
  {
    id: 109,
    name: "Pienso Premium para Gatos",
    description: "Alimento premium para gatos exigentes",
    price: 45,
    image: "/images/gato-alimento-1.jpg",
    category: "Alimentos",
    animalType: "Gatos",
    isPet: true,
  },
  {
    id: 110,
    name: "Pienso Económico para Gatos",
    description: "Opción accesible sin sacrificar calidad",
    price: 28,
    image: "/images/gato-alimento-2.jpg",
    category: "Alimentos",
    animalType: "Gatos",
    isPet: true,
  },
  // Categoría: Accesorios
  {
    id: 111,
    name: "Cama para Gatos",
    description: "Cama cómoda y suave para el descanso",
    price: 35,
    image: "/images/gato-cama-1.jpg",
    category: "Accesorios",
    animalType: "Gatos",
    isPet: true,
  },
  {
    id: 112,
    name: "Rascador para Gatos",
    description: "Rascador de varios niveles para ejercitarse",
    price: 40,
    image: "/images/gato-rascador-1.jpg",
    category: "Accesorios",
    animalType: "Gatos",
    isPet: true,
  },
  // Categoría: Complementos
  {
    id: 113,
    name: "Suplemento para Gatos",
    description: "Suplemento vitamínico para gatos",
    price: 32,
    image: "/images/gato-suplemento-1.jpg",
    category: "Complementos",
    animalType: "Gatos",
    isPet: true,
  },
  {
    id: 114,
    name: "Complemento para Gatos",
    description: "Mejora la nutrición diaria de tu gato",
    price: 38,
    image: "/images/gato-complemento-1.jpg",
    category: "Complementos",
    animalType: "Gatos",
    isPet: true,
  },
  // Categoría: Salud
  {
    id: 115,
    name: "Vacuna para Gatos",
    description: "Protege a tu gato con una vacuna esencial",
    price: 55,
    image: "/images/gato-vacuna-1.jpg",
    category: "Salud",
    animalType: "Gatos",
    isPet: true,
  },
  {
    id: 116,
    name: "Antipulgas para Gatos",
    description: "Tratamiento efectivo contra pulgas para gatos",
    price: 42,
    image: "/images/gato-antipulgas-1.jpg",
    category: "Salud",
    animalType: "Gatos",
    isPet: true,
  },

  // ----- HÁMSTERS -----
  // Categoría: Alimentos
  {
    id: 117,
    name: "Pienso para Hámsters",
    description: "Alimento balanceado especialmente formulado",
    price: 20,
    image: "/images/hamster-alimento-1.jpg",
    category: "Alimentos",
    animalType: "Hámsters",
    isPet: true,
  },
  {
    id: 118,
    name: "Pienso Especial para Hámsters",
    description: "Fórmula especial para la energía de tu hámster",
    price: 22,
    image: "/images/hamster-alimento-2.jpg",
    category: "Alimentos",
    animalType: "Hámsters",
    isPet: true,
  },
  // Categoría: Accesorios
  {
    id: 119,
    name: "Rueda para Hámsters",
    description: "Rueda de ejercicio para mantener activo a tu hámster",
    price: 15,
    image: "/images/hamster-rueda-1.jpg",
    category: "Accesorios",
    animalType: "Hámsters",
    isPet: true,
  },
  {
    id: 120,
    name: "Casa para Hámsters",
    description: "Pequeña casita para que tu hámster se esconda",
    price: 18,
    image: "/images/hamster-casa-1.jpg",
    category: "Accesorios",
    animalType: "Hámsters",
    isPet: true,
  },
  // Categoría: Complementos
  {
    id: 121,
    name: "Suplemento para Hámsters",
    description: "Suplemento vitamínico para la salud de tu hámster",
    price: 10,
    image: "/images/hamster-suplemento-1.jpg",
    category: "Complementos",
    animalType: "Hámsters",
    isPet: true,
  },
  {
    id: 122,
    name: "Complemento para Hámsters",
    description: "Ayuda nutricional para hámsters activos",
    price: 12,
    image: "/images/hamster-complemento-1.jpg",
    category: "Complementos",
    animalType: "Hámsters",
    isPet: true,
  },
  // Categoría: Salud
  {
    id: 123,
    name: "Vacuna para Hámsters",
    description: "Vacuna preventiva para mantener a salvo a tu hámster",
    price: 25,
    image: "/images/hamster-vacuna-1.jpg",
    category: "Salud",
    animalType: "Hámsters",
    isPet: true,
  },
  {
    id: 124,
    name: "Tratamiento Antipulgas para Hámsters",
    description: "Protege a tu hámster de parásitos",
    price: 20,
    image: "/images/hamster-antipulgas-1.jpg",
    category: "Salud",
    animalType: "Hámsters",
    isPet: true,
  },
];

/* ================================
   Productos para Animales Zootécnicos
   ================================ */
// Para este grupo usaremos cinco tipos de animales:
// "Vacas", "Toros", "Caballos", "Gallos" y "Bovinos" con las mismas categorías.

export const productsForZootecnicos: Product[] = [
  // ----- VACAS -----
  // Categoría: Alimentos
  {
    id: 1,
    name: "Pienso Premium para Vacas",
    description: "Alimento balanceado para vacas lecheras",
    price: 49.99,
    image: "/images/vaca-alimento-1.jpg",
    category: "Alimentos",
    animalType: "Vacas",
    isPet: false,
  },
  {
    id: 2,
    name: "Pienso Económico para Vacas",
    description: "Opción económica sin perder calidad",
    price: 39.99,
    image: "/images/vaca-alimento-2.jpg",
    category: "Alimentos",
    animalType: "Vacas",
    isPet: false,
  },
  // Categoría: Accesorios
  {
    id: 3,
    name: "Silla para Vacas",
    description: "Accesorio de confort para vacas",
    price: 29.99,
    image: "/images/vaca-accesorio-1.jpg",
    category: "Accesorios",
    animalType: "Vacas",
    isPet: false,
  },
  {
    id: 4,
    name: "Manta para Vacas",
    description: "Manta para el confort en el establo",
    price: 34.99,
    image: "/images/vaca-accesorio-2.jpg",
    category: "Accesorios",
    animalType: "Vacas",
    isPet: false,
  },
  // Categoría: Complementos
  {
    id: 5,
    name: "Suplemento para Vacas",
    description: "Suplemento vitamínico para vacas",
    price: 44.99,
    image: "/images/vaca-complemento-1.jpg",
    category: "Complementos",
    animalType: "Vacas",
    isPet: false,
  },
  {
    id: 6,
    name: "Complemento Mineral para Vacas",
    description: "Complemento mineral para mejorar la digestión",
    price: 42.99,
    image: "/images/vaca-complemento-2.jpg",
    category: "Complementos",
    animalType: "Vacas",
    isPet: false,
  },
  // Categoría: Salud
  {
    id: 7,
    name: "Vacuna para Vacas",
    description: "Vacuna preventiva para el ganado",
    price: 59.99,
    image: "/images/vaca-salud-1.jpg",
    category: "Salud",
    animalType: "Vacas",
    isPet: false,
  },
  {
    id: 8,
    name: "Antiparasitario para Vacas",
    description: "Tratamiento contra parásitos en vacas",
    price: 49.99,
    image: "/images/vaca-salud-2.jpg",
    category: "Salud",
    animalType: "Vacas",
    isPet: false,
  },

  // ----- TOROS -----
  // Categoría: Alimentos
  {
    id: 9,
    name: "Pienso Premium para Toros",
    description: "Alimento balanceado para toros",
    price: 55.99,
    image: "/images/toro-alimento-1.jpg",
    category: "Alimentos",
    animalType: "Toros",
    isPet: false,
  },
  {
    id: 10,
    name: "Pienso Económico para Toros",
    description: "Alimento económico para toros",
    price: 45.99,
    image: "/images/toro-alimento-2.jpg",
    category: "Alimentos",
    animalType: "Toros",
    isPet: false,
  },
  // Categoría: Accesorios
  {
    id: 11,
    name: "Arnés para Toros",
    description: "Arnés de seguridad para toros",
    price: 35.99,
    image: "/images/toro-accesorio-1.jpg",
    category: "Accesorios",
    animalType: "Toros",
    isPet: false,
  },
  {
    id: 12,
    name: "Funda para Toros",
    description: "Funda protectora para toros",
    price: 30.99,
    image: "/images/toro-accesorio-2.jpg",
    category: "Accesorios",
    animalType: "Toros",
    isPet: false,
  },
  // Categoría: Complementos
  {
    id: 13,
    name: "Suplemento para Toros",
    description: "Suplemento vitamínico para toros",
    price: 50.99,
    image: "/images/toro-complemento-1.jpg",
    category: "Complementos",
    animalType: "Toros",
    isPet: false,
  },
  {
    id: 14,
    name: "Complemento Mineral para Toros",
    description: "Complemento mineral para toros",
    price: 48.99,
    image: "/images/toro-complemento-2.jpg",
    category: "Complementos",
    animalType: "Toros",
    isPet: false,
  },
  // Categoría: Salud
  {
    id: 15,
    name: "Vacuna para Toros",
    description: "Vacuna preventiva para toros",
    price: 65.99,
    image: "/images/toro-salud-1.jpg",
    category: "Salud",
    animalType: "Toros",
    isPet: false,
  },
  {
    id: 16,
    name: "Antiparasitario para Toros",
    description: "Tratamiento antiparasitario para toros",
    price: 55.99,
    image: "/images/toro-salud-2.jpg",
    category: "Salud",
    animalType: "Toros",
    isPet: false,
  },

  // ----- CABALLOS -----
  // Categoría: Alimentos
  {
    id: 17,
    name: "Pienso Premium para Caballos",
    description: "Alimento premium para caballos",
    price: 65.99,
    image: "/images/caballo-alimento-1.jpg",
    category: "Alimentos",
    animalType: "Caballos",
    isPet: false,
  },
  {
    id: 18,
    name: "Pienso Económico para Caballos",
    description: "Opción económica para caballos",
    price: 55.99,
    image: "/images/caballo-alimento-2.jpg",
    category: "Alimentos",
    animalType: "Caballos",
    isPet: false,
  },
  // Categoría: Accesorios
  {
    id: 19,
    name: "Silla para Caballos",
    description: "Silla de montar para caballos",
    price: 75.99,
    image: "/images/caballo-accesorio-1.jpg",
    category: "Accesorios",
    animalType: "Caballos",
    isPet: false,
  },
  {
    id: 20,
    name: "Freno para Caballos",
    description: "Freno de seguridad para caballos",
    price: 70.99,
    image: "/images/caballo-accesorio-2.jpg",
    category: "Accesorios",
    animalType: "Caballos",
    isPet: false,
  },
  // Categoría: Complementos
  {
    id: 21,
    name: "Suplemento para Caballos",
    description: "Suplemento vitamínico para caballos",
    price: 60.99,
    image: "/images/caballo-complemento-1.jpg",
    category: "Complementos",
    animalType: "Caballos",
    isPet: false,
  },
  {
    id: 22,
    name: "Complemento para Caballos",
    description: "Complemento nutricional para caballos",
    price: 58.99,
    image: "/images/caballo-complemento-2.jpg",
    category: "Complementos",
    animalType: "Caballos",
    isPet: false,
  },
  // Categoría: Salud
  {
    id: 23,
    name: "Vacuna para Caballos",
    description: "Vacuna preventiva para caballos",
    price: 70.99,
    image: "/images/caballo-salud-1.jpg",
    category: "Salud",
    animalType: "Caballos",
    isPet: false,
  },
  {
    id: 24,
    name: "Antiparasitario para Caballos",
    description: "Tratamiento antiparasitario para caballos",
    price: 65.99,
    image: "/images/caballo-salud-2.jpg",
    category: "Salud",
    animalType: "Caballos",
    isPet: false,
  },

  // ----- GALLOS -----
  // Categoría: Alimentos
  {
    id: 25,
    name: "Pienso Premium para Gallos",
    description: "Alimento premium para gallos",
    price: 40.99,
    image: "/images/gallo-alimento-1.jpg",
    category: "Alimentos",
    animalType: "Gallos",
    isPet: false,
  },
  {
    id: 26,
    name: "Pienso Económico para Gallos",
    description: "Opción económica para gallos",
    price: 35.99,
    image: "/images/gallo-alimento-2.jpg",
    category: "Alimentos",
    animalType: "Gallos",
    isPet: false,
  },
  // Categoría: Accesorios
  {
    id: 27,
    name: "Pluma Decorativa para Gallos",
    description: "Accesorio decorativo para gallos",
    price: 25.99,
    image: "/images/gallo-accesorio-1.jpg",
    category: "Accesorios",
    animalType: "Gallos",
    isPet: false,
  },
  {
    id: 28,
    name: "Arnés para Gallos",
    description: "Arnés funcional para gallos",
    price: 30.99,
    image: "/images/gallo-accesorio-2.jpg",
    category: "Accesorios",
    animalType: "Gallos",
    isPet: false,
  },
  // Categoría: Complementos
  {
    id: 29,
    name: "Suplemento para Gallos",
    description: "Suplemento vitamínico para gallos",
    price: 33.99,
    image: "/images/gallo-complemento-1.jpg",
    category: "Complementos",
    animalType: "Gallos",
    isPet: false,
  },
  {
    id: 30,
    name: "Complemento para Gallos",
    description: "Complemento nutricional para gallos",
    price: 31.99,
    image: "/images/gallo-complemento-2.jpg",
    category: "Complementos",
    animalType: "Gallos",
    isPet: false,
  },
  // Categoría: Salud
  {
    id: 31,
    name: "Vacuna para Gallos",
    description: "Vacuna preventiva para gallos",
    price: 38.99,
    image: "/images/gallo-salud-1.jpg",
    category: "Salud",
    animalType: "Gallos",
    isPet: false,
  },
  {
    id: 32,
    name: "Antiparasitario para Gallos",
    description: "Tratamiento antiparasitario para gallos",
    price: 36.99,
    image: "/images/gallo-salud-2.jpg",
    category: "Salud",
    animalType: "Gallos",
    isPet: false,
  },

  // ----- BOVINOS -----
  // Categoría: Alimentos
  {
    id: 33,
    name: "Pienso Premium para Bovinos",
    description: "Alimento premium para bovinos",
    price: 60.99,
    image: "/images/bovino-alimento-1.jpg",
    category: "Alimentos",
    animalType: "Bovinos",
    isPet: false,
  },
  {
    id: 34,
    name: "Pienso Económico para Bovinos",
    description: "Alimento económico para bovinos",
    price: 50.99,
    image: "/images/bovino-alimento-2.jpg",
    category: "Alimentos",
    animalType: "Bovinos",
    isPet: false,
  },
  // Categoría: Accesorios
  {
    id: 35,
    name: "Arnés para Bovinos",
    description: "Arnés robusto para manejo de bovinos",
    price: 40.99,
    image: "/images/bovino-accesorio-1.jpg",
    category: "Accesorios",
    animalType: "Bovinos",
    isPet: false,
  },
  {
    id: 36,
    name: "Funda para Bovinos",
    description: "Funda protectora para bovinos",
    price: 38.99,
    image: "/images/bovino-accesorio-2.jpg",
    category: "Accesorios",
    animalType: "Bovinos",
    isPet: false,
  },
  // Categoría: Complementos
  {
    id: 37,
    name: "Suplemento para Bovinos",
    description: "Suplemento vitamínico para bovinos",
    price: 45.99,
    image: "/images/bovino-complemento-1.jpg",
    category: "Complementos",
    animalType: "Bovinos",
    isPet: false,
  },
  {
    id: 38,
    name: "Complemento Mineral para Bovinos",
    description: "Complemento mineral para bovinos",
    price: 43.99,
    image: "/images/bovino-complemento-2.jpg",
    category: "Complementos",
    animalType: "Bovinos",
    isPet: false,
  },
  // Categoría: Salud
  {
    id: 39,
    name: "Vacuna para Bovinos",
    description: "Vacuna preventiva para bovinos",
    price: 65.99,
    image: "/images/bovino-salud-1.jpg",
    category: "Salud",
    animalType: "Bovinos",
    isPet: false,
  },
  {
    id: 40,
    name: "Antiparasitario para Bovinos",
    description: "Tratamiento antiparasitario para bovinos",
    price: 60.99,
    image: "/images/bovino-salud-2.jpg",
    category: "Salud",
    animalType: "Bovinos",
    isPet: false,
  },
];
